[
    {
        "titleEnglish": "Journey of the Brave",
        "titleJpRoman": "Yuusha no Tabi",
        "titleJpKanji": "勇者の旅",
        "description": "A young hero sets out on a journey to save his kingdom from an ancient curse.",
        "type": "TV",
        "episodes": 24,
        "episodeDuration": 25,
        "premiereSeason": "Fall 2023",
        "genre": ["Action", "Adventure", "Fantasy"],
        "prequel": null,
        "sequel": 85,
        "demographic": "Shounen",
        "airDate": "2023-10-01",
        "endDate": "2024-03-30",
        "studio": "Silver Studio"
    },
    {
        "titleEnglish": "Magic Academy Chronicles",
        "titleJpRoman": "Mahou Gakuen Monogatari",
        "titleJpKanji": "魔法学園物語",
        "description": "Follows students in a prestigious magic academy as they unravel dark secrets.",
        "type": "OVA",
        "episodes": 12,
        "episodeDuration": 30,
        "premiereSeason": "Winter 2024",
        "genre": ["Fantasy", "Mystery", "Drama"],
        "prequel": 83,
        "sequel": null,
        "demographic": "Shoujo",
        "airDate": "2024-01-05",
        "endDate": "2024-04-15",
        "studio": "Mystic Works"
    },
    {
        "titleEnglish": "Samurai Legends",
        "titleJpRoman": "Samurai Densetsu",
        "titleJpKanji": "侍伝説",
        "description": "A tale of a wandering samurai facing foes and inner turmoil in feudal Japan.",
        "type": "Movie",
        "episodes": 1,
        "episodeDuration": 120,
        "premiereSeason": "Summer 2023",
        "genre": ["Action", "Historical", "Drama"],
        "prequel": null,
        "sequel": null,
        "demographic": "Seinen",
        "airDate": "2023-07-15",
        "endDate": null,
        "studio": "Samurai Pictures"
    },
    {
        "titleEnglish": "Dreamscape Warriors",
        "titleJpRoman": "Yume no Senshi",
        "titleJpKanji": "夢の戦士",
        "description": "Warriors travel through dream worlds to battle an evil that threatens all reality.",
        "type": "TV",
        "episodes": 20,
        "episodeDuration": 22,
        "premiereSeason": "Spring 2023",
        "genre": ["Adventure", "Fantasy", "Psychological"],
        "prequel": null,
        "sequel": 86,
        "demographic": "Josei",
        "airDate": "2023-04-10",
        "endDate": "2023-09-05",
        "studio": "DreamWorks Studio"
    },
    {
        "titleEnglish": "Galactic Guardians",
        "titleJpRoman": "Ginga no Shugo",
        "titleJpKanji": "銀河の守護",
        "description": "A sci-fi epic following a team of guardians protecting the galaxy from threats.",
        "type": "TV",
        "episodes": 50,
        "episodeDuration": 24,
        "premiereSeason": "Winter 2025",
        "genre": ["Sci-Fi", "Adventure", "Mecha"],
        "prequel": 84,
        "sequel": null,
        "demographic": "Seinen",
        "airDate": "2025-01-10",
        "endDate": "2026-01-10",
        "studio": "Galactic Studios"
    }
]